# Generated by Django 4.2.7 on 2023-11-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_name', models.CharField(max_length=255)),
                ('duration', models.FloatField()),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.annotator')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audio')),
            ],
        ),
    ]
