# Generated by Django 4.2.7 on 2023-11-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audio_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(default='default_audio.mp3', upload_to='audio/'),
        ),
    ]
