# Generated by Django 4.2.7 on 2023-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_remove_audio_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1, unique=True)),
            ],
        ),
    ]
