# Generated by Django 4.2.7 on 2023-11-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_characterset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(default='default_audio.mp3', upload_to='recordings/'),
        ),
    ]
